version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: xamfoo/arch-dev
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Pull Docker image
          command: |
            test "$USE_CACHE" = "1" && docker pull $IMAGE_NAME:latest || true
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest --cache-from $IMAGE_NAME:latest .
      - run:
          name: Test Docker image
          command: |
            [[ -f ./test.sh ]] && ./test.sh || true
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
